### ISSUE TITLE
No auto-refresh after hitting breakpoint

### ISSUE THREAD

**Issue by phcerdan** [dbgx/lldb.nvim#31]
The editor, backtrace and locals windows do not update automatically after a breakpoint stop.
I have to interact with lldb to trigger the update, for example, `:LL print something`. (even if `something` does not exist)

Is this the expected behavior? Or is there any option to tweak it? Thanks!

**Comment by critiqjo** [comment]
> Is this the expected behavior?

No, that would be a bug! Does this happen every single time? Here is an description of what goes on when a breakpoint is hit:

First, the control comes [here](https://github.com/critiqjo/lldb.nvim/blob/b8d2422/rplugin/python/lldb_nvim/controller.py#L297), and eventually calls [this](https://github.com/critiqjo/lldb.nvim/blob/b8d2422/rplugin/python/lldb_nvim/controller.py#L328) which executes [this](https://github.com/critiqjo/lldb.nvim/blob/b8d2422/rplugin/python/lldb_nvim/vim_buffers.py#L154) to update all buffers. And [this](https://github.com/critiqjo/lldb.nvim/blob/b8d2422/rplugin/python/lldb_nvim/vim_x.py#L122) is the innermost call where the actual updates happen (where it decides to invoke Neovim RPC to update the buffers only if the new `content` [differs](https://github.com/critiqjo/lldb.nvim/blob/b8d2422/rplugin/python/lldb_nvim/vim_x.py#L139-L145) from the old).

**Comment by phcerdan** [comment]
After a play test, I've found that it only happens when I remove the "default" start breakpoint AND there is some command line argument read involved.

I can reproduce it with your test file: [ab.c](https://github.com/critiqjo/lldb.nvim/blob/master/test/ab.c). If I remove the starting break point in [L14](https://github.com/critiqjo/lldb.nvim/blob/master/test/ab.c#L14), and put it, in [L18](https://github.com/critiqjo/lldb.nvim/blob/master/test/ab.c#L18).

I don't get a prompt asking me to enter a number, but I can enter it anyway, and the programs ends properly, however it doesn't hit the L18 breakpoint.

If I change the call to `scanf` in [L15](https://github.com/critiqjo/lldb.nvim/blob/master/test/ab.c#L15) for `a=20;`, I can remove the default starting breakpoint, put it in L18 and it works good.

Does this happens to you too? Maybe it is unrelated with your plugin, and related with a [bug](https://llvm.org/bugs/show_bug.cgi?id=28898) of lldb in arch...

**Comment by critiqjo** [comment]
A bit busy now... I'll try it out in a few days.

**Comment by critiqjo** [comment]
I don't see any problems with auto-refreshing in general. But, as you mentioned, if I remove the breakpoint at line 14 (keeping scanf), then "Enter a number: " is not printed (whatever I do, it does not get printed at this point). But if I input some number (anyway) then the execution continues and hits the first breakpoint, and all that is to be printed gets printed.

I don't think this is a problem with the auto-refresh mechanism, though. I believe this is because lldb failed to immediately [notify](https://github.com/critiqjo/lldb.nvim/blob/b8d2422/rplugin/python/lldb_nvim/controller.py#L174) the plugin of receiving stuff in stdout in that particular situation.

**Comment by johncf** [comment]
cc #59
