### ISSUE TITLE
Issues with frame variable when examining std::vector

### ISSUE THREAD

**Issue by jkunlin** [dbgx/lldb.nvim#50]
Command 'frame variable' (so as the locals buffer) always shows that 'size = 0', while it works well with command 'display vec'.

I test with the run.sh, and here is the report:

Note: `:LL-` commands are not bound with this test instance            
error: libc.so.6 0x003de11b: DW_TAG_variable has an invalid location: 
DW_OP_lit13
DW_OP_const8s(0x0000000000000000)

**Comment by jkunlin** [comment]
"display" dose not print any message in log buffer as well.

BTW, everything goes well when using terminal.

**Comment by critiqjo** [comment]
> Command 'frame variable' (so as the locals buffer) always shows that 'size = 0', while it works well with command 'display vec'.

Yes, I'm aware of this bug. But this does not have anything to do with this plugin. This is a bug in their Python API. I'm not really sure why, but there are many breakages when working from the Python API which works perfectly with the `lldb` tool (another example is [remote debugging]).

[remote debugging]: https://github.com/critiqjo/lldb.nvim#remote-debugging-does-not-work

> "display" dose not print any message in log buffer as well.

`display` command is, I believe, well-tied with the front-end. So in order to get it work in this plugin, significant work may have to be done. (I am unable to recall much details about this, so I might be wrong.)

I'll leave this issue open until a "Known Issues" section is added to README.

**Comment by jkunlin** [comment]
Is there any way to make "frame variable" works correctly?

**Comment by critiqjo** [comment]
@jkunlin It _might_ work in [remote debugging](https://github.com/critiqjo/lldb.nvim#remote-debugging-does-not-work) mode. Start the server using `lldb-server p --server --listen 2345` so that the server doesn't exit when the client leaves. (Note: For security reasons, it might be good to use a firewall to block remote connections to that port, at least while using the `--server` switch.)

**Comment by jkunlin** [comment]
It doesn't works in remote debugging mode too.

**Comment by johncf** [comment]
cc #59
