### ISSUE TITLE
Multithread debug issues

### ISSUE THREAD

**Issue by lenfien** [dbgx/lldb.nvim#51]
I have just touched vim. My English is not very good, please feel free to laugh at me.
I used lldb.nvim to debug multithreaded code when there was a bug.
First, I use the "thread select" command to select a thread, and then enter the "LL next" command, lldb.nvim will automatically switch to the main thread. I have to choose my target thread over and over again.
After testing, this bug does not appear to use lldb directly.
I captured a video as follows:

![lldb_bug](https://cloud.githubusercontent.com/assets/12644010/25137359/1e9602a2-248a-11e7-9b7a-12220d596280.gif)

**Comment by critiqjo** [comment]
Wow! Thanks for the rich bug report. Unfortunately, this is probably due to the same reason as #50 (which is that it has nothing to do with this plugin; just bugs within LLDB's python API).

To elaborate a little more, commands executed using `:LL ` are directly [processed](https://github.com/critiqjo/lldb.nvim/blob/master/rplugin/python/lldb_nvim/controller.py#L257) by a `SBCommandInterpreter` object. The only extra commands that are executed by the plugin are [these](https://github.com/critiqjo/lldb.nvim/blob/master/rplugin/python/lldb_nvim/vim_buffers.py#L18-L23) for populating the vim buffers with relevant information. Fetching the [breakpoints list](https://github.com/critiqjo/lldb.nvim/blob/master/rplugin/python/lldb_nvim/vim_buffers.py#L112) for placing the bp-signs, and the [program counter list](https://github.com/critiqjo/lldb.nvim/blob/master/rplugin/python/lldb_nvim/vim_buffers.py#L62-L63) for placing the pc-signs all use LLDB's python APIs, and are not supposed to affect the selected thread.

In short, there's nothing I can do! (And I refuse to patch up an upstream bug in plugin either.) The more important issue is that lldb-devs don't seem to care about Python API bugs either (for some years now). I think they are expecting plugins to use their new [machine interface](http://llvm.org/viewvc/llvm-project/lldb/trunk/tools/lldb-mi/MIReadMe.txt?view=co) which is developed to be compatible with [GdbMI](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html) which claims to be becoming a [de-facto standard](https://wiki.linuxfoundation.org/en/Debugger_Machine_Interface_(DMI)).

So you might ask: Does this project have no future? That's right, I'm abandoning this project!! :sweat_smile: ...in favor of [gdb.vim](https://github.com/johncf/gdb.vim), which uses Gdb/MI through [pygdbmi](https://github.com/cs01/pygdbmi)! I'm hoping to resume developing it in a month or two.

PS: What tool did you use for editing the video to add those text bubbles?

**Comment by lenfien** [comment]
Thank you so much ! The tool is Camtisia 3. 
So, It seems the machine interface of lldb and gdb is future. This is the most useful information I get because of my novice. 
I am eager to use your new plugin~ Please complete as soon as possible， just can not wait～😊

**Comment by johncf** [comment]
cc #59

**Comment by mellery451** [comment]
the link in the README led me here - does this mean that [gdb.vim](https://github.com/johncf/gdb.vim) is the way forward even for LLDB users? It unclear to me if it's intended to work using lldb-mi or if it only supports gdb/mi. Any clarification appreciated.

**Comment by johncf** [comment]
@mellery451 I stopped developing `gdb.vim` after I met with a roadblock from vim's side at the time (it did not redraw the buffers on windows that are not focused, when the buffers are updated remotely). A `gdb.nvim` project is definitely very feasible, but currently I'm invested on other projects that I don't have time for it.

**Comment by johncf** [comment]
@lanza Looks very interesting. I'm sure it'll have long-term support for many debuggers if something as big and popular as VSCode is backing it. Unfortunately, I won't be updating lldb.nvim anymore, nor I would review PRs for this since a large portion of the code needs to be changed and it does not make sense to make radical changes to this project in the absence of an active maintainer.

But you're free to copy any part of the source code (fork or not) if that helps you to create and maintain your own independent project.

**Comment by BatmanAoD** [comment]
@critiqjo Since the `README` points to your comment above, would you mind updating the gdb.vim link to point to the current location (under `dbgx`), since it's currently broken? I suppose you could update the `README` instead, but at least by editing the comment you'd provide a slightly more robust trail of breadcrumbs than the one I just followed! 😆
